providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "gdal", "geos", "proj", "gcc"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/uvicorn satelite:app --host 0.0.0.0 --port $PORT"
